- hosts: all
  gather_facts: no
  tasks:
  - name: "Install aptitude"
    shell: apt -y install aptitude
    become: yes

  ## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  - name: "Update OS"
    apt: update_cache=yes upgrade=yes autoremove=yes autoclean=yes
    become: yes
    tags: os_update

  - name: "Update OS dist-upgrade"
    apt: update_cache=yes upgrade=dist autoremove=yes autoclean=yes
    become: yes
    tags: os_update

  - name: "Install Packages"
    apt:
     name: ['chrony']
    tags: install_packages
    become: yes

  - name: "Configure NTP"
    replace:
      dest: '/etc/chrony/chrony.conf'
      regexp: '^pool 0\.ubuntu\.pool\.ntp\.org iburst maxsources 1$'
      replace: 'pool ntp.nict.jp iburst maxsources 2'
    become: yes

  - name: "Apply NTP"
    systemd:
      name: 'chrony'
      state: 'restarted'
      enabled: 'yes'
    become: yes
