- hosts: all
  tasks:
  - name: Install aptitude
    shell: apt -y install aptitude python
    become: yes
  ## http://docs.ansible.com/ansible/latest/apt_module.html
  - name: OS Update
    apt: update_cache=yes upgrade=yes autoremove=yes autoclean=yes
    become: yes
    tags: os_update

  - name: install Packages
    apt:
     name: ['ntp']
    tags: install_packages
    become: yes
